site_name: Techniques de programmation
site_url: https://github.io/yostane/cours-techniques-de-programmation

nav:
  - Introduction: index.md
  - POO: poo.md

plugins:
  - search
#  - pdf-export
#  - with-pdf
#author: WHO
#copyright: ANY TEXT
#
#cover: false
#back_cover: true
#cover_title: TITLE TEXT
#cover_subtitle: SUBTITLE TEXT
#custom_template_path: TEMPLATES PATH
#
#toc_title: TOC TITLE TEXT
#heading_shift: false
#toc_level: 3
#ordered_chapter_level: 2
#excludes_children:
#    - 'release-notes/:upgrading'
#    - 'release-notes/:changelog'
#
#exclude_pages:
#    - 'bugs/'
#    - 'appendix/contribute/'
#convert_iframe:
#    - src: IFRAME SRC
#      img: POSTER IMAGE URL
#      text: ALTERNATE TEXT
#    - src: ...
#two_columns_level: 3
#
#render_js: true
#headless_chrome_path: headless-chromium
#
#output_path: any-place/document.pdf
#enabled_if_env: ENABLE_PDF_EXPORT
#
#debug_html: true
#show_anchors: true
#verbose: true

theme:
  name: material
