site_name: Techniques de programmation
site_url: https://yostane.github.io/cours-techniques-de-programmation/
repo_url: https://github.com/yostane/cours-techniques-de-programmation
repo_name: yostane/cours-techniques-de-programmation
edit_uri: ""

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/yostane

nav:
  - Introduction: index.md
  - Généralités: generalites.md
  - POO: poo.md
  - Programmation fonctionnelle: func.md
  - Pratiques et styles: avance.md
  - Mini-projet: projet.md
  - Etiquettes: tags.md

plugins:
  - search
  - tags:
      tags_file: tags.md
  - i18n:
      material_alternate: true
      default_language: fr
      languages:
        fr:
          name: Français
          build: true

theme:
  name: material
  features:
    - navigation.top
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: lime
      accent: green
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: lime
      accent: green

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.inlinehilite
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets:
      base_path:
        ["material/poo", "material/functional", "material/generalities"]
