name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-static-i18n
      - run: pip install mdx_truly_sane_lists
      - run: mkdocs gh-deploy --force
      - run: pip install mkdocs-glightbox
